typography_spectrum: 0.18544405000284314
color:
  brandStrength: 0.5689069274812937
  lightness: 0.19960799114778638
  saturation: 0.9484726137015969
  rhythmicContrast: 0.9882961581461132
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.3073361157439649
name: Ben Botkin Site
navigation:
  - name: Music
    url: 'https://soundcloud.com/benbotkin/sets/bb-portfolio'
    type: external
title: Benjamin Botkin
description: Composer
